export enum RepositoryEnum {
  USER_REPOSITORY = 'USER_REPOSITORY',

  ASSET_DETAIL_REPOSITORY = 'ASSET_DETAIL_REPOSITORY',
  ASSET_REPOSITORY = 'ASSET_REPOSITORY',
  CATALOGUE_TYPE_REPOSITORY = 'CATALOGUE_TYPES_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  CONSUMABLES_REPOSITORY = 'CONSUMABLES_REPOSITORY',
  MATERIAL_REPOSITORY = 'MATERIAL_REPOSITORY',
}
