export enum RepositoryEnum {
  USER_REPOSITORY = 'USER_REPOSITORY',

  AREA_REPOSITORY = 'AREA_REPOSITORY',
  CATALOGUE_TYPE_REPOSITORY = 'CATALOGUE_TYPE_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  MATERIAL_REPOSITORY = 'MATERIAL_REPOSITORY',
}
